#pragma once

#include "soh/Flags.h"

// clang-format off
namespace Flags {
    const Flag GREETED_BY_SARIA = Flag::FromInfTable(0x00);
    const Flag INFTABLE_UNKNOWN_01 = Flag::FromInfTable(0x01);
    const Flag INFTABLE_UNKNOWN_03 = Flag::FromInfTable(0x03);
    const Flag INFTABLE_UNKNOWN_05 = Flag::FromInfTable(0x05);
    const Flag INFTABLE_UNKNOWN_0C = Flag::FromInfTable(0x0C);
    const Flag INFTABLE_UNKNOWN_0E = Flag::FromInfTable(0x0E);
    const Flag INFTABLE_UNKNOWN_10 = Flag::FromInfTable(0x10);
    const Flag INFTABLE_UNKNOWN_15 = Flag::FromInfTable(0x15);
    const Flag INFTABLE_UNKNOWN_17 = Flag::FromInfTable(0x17);
    const Flag INFTABLE_UNKNOWN_19 = Flag::FromInfTable(0x19);
    const Flag INFTABLE_UNKNOWN_1E = Flag::FromInfTable(0x1E);
    const Flag INFTABLE_UNKNOWN_22 = Flag::FromInfTable(0x22);
    const Flag INFTABLE_UNKNOWN_24 = Flag::FromInfTable(0x24);
    const Flag INFTABLE_UNKNOWN_26 = Flag::FromInfTable(0x26);
    const Flag INFTABLE_UNKNOWN_28 = Flag::FromInfTable(0x28);
    const Flag INFTABLE_UNKNOWN_2A = Flag::FromInfTable(0x2A);
    const Flag INFTABLE_UNKNOWN_2B = Flag::FromInfTable(0x2B);
    const Flag INFTABLE_UNKNOWN_2E = Flag::FromInfTable(0x2E);
    const Flag INFTABLE_UNKNOWN_2F = Flag::FromInfTable(0x2F);
    const Flag INFTABLE_UNKNOWN_30 = Flag::FromInfTable(0x30);
    const Flag INFTABLE_UNKNOWN_41 = Flag::FromInfTable(0x41);
    const Flag INFTABLE_UNKNOWN_47 = Flag::FromInfTable(0x47);
    const Flag INFTABLE_UNKNOWN_51 = Flag::FromInfTable(0x51);
    const Flag INFTABLE_UNKNOWN_59 = Flag::FromInfTable(0x59);
    const Flag INFTABLE_UNKNOWN_61 = Flag::FromInfTable(0x61);
    const Flag INFTABLE_UNKNOWN_66 = Flag::FromInfTable(0x66);
    const Flag INFTABLE_UNKNOWN_6A = Flag::FromInfTable(0x6A);
    const Flag INFTABLE_UNKNOWN_6C = Flag::FromInfTable(0x6C);
    const Flag INFTABLE_UNKNOWN_71 = Flag::FromInfTable(0x71);
    const Flag SHOWED_ZELDAS_LETTER_TO_GATE_GUARD = Flag::FromInfTable(0x76);
    const Flag GATE_GUARD_PUT_ON_KEATON_MASK = Flag::FromInfTable(0x77);
    const Flag TALKED_TO_TALON_IN_RANCH_HOUSE = Flag::FromInfTable(0x7E);
    const Flag MET_CHILD_MALON_AT_CASTLE_OR_MARKET = Flag::FromInfTable(0x84);
    const Flag CHILD_MALON_SAID_EPONA_WAS_AFRAID_OF_YOU = Flag::FromInfTable(0x85);
    const Flag INF_ENTERED_HYRULE_CASTLE = Flag::FromInfTable(0x8B);
    const Flag INFTABLE_UNKNOWN_8C = Flag::FromInfTable(0x8C);
    const Flag INFTABLE_UNKNOWN_8D = Flag::FromInfTable(0x8D);
    const Flag INFTABLE_UNKNOWN_8E = Flag::FromInfTable(0x8E);
    const Flag INFTABLE_UNKNOWN_94 = Flag::FromInfTable(0x94);
    const Flag INFTABLE_UNKNOWN_97 = Flag::FromInfTable(0x97);
    const Flag SPOKE_TO_INGO_ONCE_AS_ADULT = Flag::FromInfTable(0x9A);
    const Flag INFTABLE_UNKNOWN_A2 = Flag::FromInfTable(0xA2);
    const Flag INFTABLE_UNKNOWN_AB = Flag::FromInfTable(0xAB);
    const Flag INFTABLE_UNKNOWN_B0 = Flag::FromInfTable(0xB0);
    const Flag INFTABLE_UNKNOWN_B1 = Flag::FromInfTable(0xB1);
    const Flag INFTABLE_UNKNOWN_B4 = Flag::FromInfTable(0xB4);
    const Flag SPOKE_TO_POE_COLLECTOR_IN_RUINED_MARKET = Flag::FromInfTable(0xB6);
    const Flag INFTABLE_UNKNOWN_B7 = Flag::FromInfTable(0xB7);
    const Flag INFTABLE_UNKNOWN_B8 = Flag::FromInfTable(0xB8);
    const Flag INFTABLE_UNKNOWN_B9 = Flag::FromInfTable(0xB9);
    const Flag INFTABLE_UNKNOWN_BC = Flag::FromInfTable(0xBC);
    const Flag INFTABLE_UNKNOWN_C0 = Flag::FromInfTable(0xC0);
    const Flag INFTABLE_UNKNOWN_C1 = Flag::FromInfTable(0xC1);
    const Flag INFTABLE_UNKNOWN_C2 = Flag::FromInfTable(0xC2);
    const Flag INFTABLE_UNKNOWN_C3 = Flag::FromInfTable(0xC3);
    const Flag INFTABLE_UNKNOWN_C4 = Flag::FromInfTable(0xC4);
    const Flag INFTABLE_UNKNOWN_C5 = Flag::FromInfTable(0xC5);
    const Flag INFTABLE_UNKNOWN_C6 = Flag::FromInfTable(0xC6);
    const Flag INFTABLE_UNKNOWN_C7 = Flag::FromInfTable(0xC7);
    const Flag INFTABLE_UNKNOWN_C8 = Flag::FromInfTable(0xC8);
    const Flag INFTABLE_UNKNOWN_C9 = Flag::FromInfTable(0xC9);
    const Flag INFTABLE_UNKNOWN_CA = Flag::FromInfTable(0xCA);
    const Flag INFTABLE_UNKNOWN_CB = Flag::FromInfTable(0xCB);
    const Flag INFTABLE_UNKNOWN_CC = Flag::FromInfTable(0xCC);
    const Flag INFTABLE_UNKNOWN_CD = Flag::FromInfTable(0xCD);
    const Flag INFTABLE_UNKNOWN_CE = Flag::FromInfTable(0xCE);
    const Flag INFTABLE_UNKNOWN_D0 = Flag::FromInfTable(0xD0);
    const Flag INFTABLE_UNKNOWN_D2 = Flag::FromInfTable(0xD2);
    const Flag INFTABLE_UNKNOWN_D4 = Flag::FromInfTable(0xD4);
    const Flag INFTABLE_UNKNOWN_D6 = Flag::FromInfTable(0xD6);
    const Flag INFTABLE_UNKNOWN_D8 = Flag::FromInfTable(0xD8);
    const Flag INFTABLE_UNKNOWN_D9 = Flag::FromInfTable(0xD9);
    const Flag INFTABLE_UNKNOWN_E0 = Flag::FromInfTable(0xE0);
    const Flag INFTABLE_UNKNOWN_E3 = Flag::FromInfTable(0xE3);
    const Flag INFTABLE_UNKNOWN_E6 = Flag::FromInfTable(0xE6);
    const Flag INFTABLE_UNKNOWN_EB = Flag::FromInfTable(0xEB);
    const Flag INFTABLE_UNKNOWN_F0 = Flag::FromInfTable(0xF0);
    const Flag INFTABLE_UNKNOWN_F4 = Flag::FromInfTable(0xF4);
    const Flag INFTABLE_UNKNOWN_F8 = Flag::FromInfTable(0xF8);
    const Flag INFTABLE_UNKNOWN_FC = Flag::FromInfTable(0xFC);
    const Flag GORON_CITY_DOORS_UNLOCKED = Flag::FromInfTable(0x109);
    const Flag INFTABLE_UNKNOWN_10A = Flag::FromInfTable(0x10A);
    const Flag INFTABLE_UNKNOWN_10B = Flag::FromInfTable(0x10B);
    const Flag STOPPED_GORON_LINKS_ROLLING = Flag::FromInfTable(0x10C);
    const Flag INFTABLE_UNKNOWN_10D = Flag::FromInfTable(0x10D);
    const Flag SPOKE_TO_GORON_LINK = Flag::FromInfTable(0x10E);
    const Flag INFTABLE_UNKNOWN_10F = Flag::FromInfTable(0x10F);
    const Flag INFTABLE_UNKNOWN_113 = Flag::FromInfTable(0x113);
    const Flag SPOKE_TO_DARUNIA_IN_FIRE_TEMPLE = Flag::FromInfTable(0x11A);
    const Flag INFTABLE_UNKNOWN_11E = Flag::FromInfTable(0x11E);
    const Flag INFTABLE_UNKNOWN_124 = Flag::FromInfTable(0x124);
    const Flag INFTABLE_UNKNOWN_129 = Flag::FromInfTable(0x129);
    const Flag INFTABLE_UNKNOWN_12A = Flag::FromInfTable(0x12A);
    const Flag INFTABLE_UNKNOWN_138 = Flag::FromInfTable(0x138);
    const Flag INFTABLE_UNKNOWN_139 = Flag::FromInfTable(0x139);
    const Flag INFTABLE_UNKNOWN_140 = Flag::FromInfTable(0x140); // Left her on blue switch in fork room (causes her to spawn in fork room)
    const Flag RUTO_IN_JJ_MEET_RUTO = Flag::FromInfTable(0x141); // Jumped down hole from hole room
    const Flag RUTO_IN_JJ_TALK_FIRST_TIME = Flag::FromInfTable(0x142); // in the basement
    const Flag INFTABLE_UNKNOWN_143 = Flag::FromInfTable(0x143); // Sat down in basement (causes her to get upset if this is set when actor is spawned)
    const Flag RUTO_IN_JJ_WANTS_TO_BE_TOSSED_TO_SAPPHIRE = Flag::FromInfTable(0x144); // Entered the room with the sapphire
    const Flag INFTABLE_UNKNOWN_145 = Flag::FromInfTable(0x145); // Thrown to sapphire (not kidnapped yet)
    const Flag INFTABLE_UNKNOWN_146 = Flag::FromInfTable(0x146); // Kidnapped
    const Flag INFTABLE_UNKNOWN_147 = Flag::FromInfTable(0x147); // Brought ruto back up to holes room, causes her to spawn in holes room instead of basement
    const Flag INFTABLE_UNKNOWN_160 = Flag::FromInfTable(0x160);
    const Flag INFTABLE_UNKNOWN_161 = Flag::FromInfTable(0x161);
    const Flag INFTABLE_UNKNOWN_162 = Flag::FromInfTable(0x162);
    const Flag INFTABLE_UNKNOWN_163 = Flag::FromInfTable(0x163);
    const Flag INFTABLE_UNKNOWN_164 = Flag::FromInfTable(0x164);
    const Flag INFTABLE_UNKNOWN_166 = Flag::FromInfTable(0x166);
    const Flag INFTABLE_UNKNOWN_16A = Flag::FromInfTable(0x16A);
    const Flag INFTABLE_UNKNOWN_16C = Flag::FromInfTable(0x16C);
    const Flag INFTABLE_UNKNOWN_170 = Flag::FromInfTable(0x170);
    const Flag INFTABLE_UNKNOWN_171 = Flag::FromInfTable(0x171);
    const Flag INFTABLE_UNKNOWN_172 = Flag::FromInfTable(0x172);
    const Flag INFTABLE_UNKNOWN_176 = Flag::FromInfTable(0x176);
    const Flag INFTABLE_UNKNOWN_178 = Flag::FromInfTable(0x178);
    const Flag INFTABLE_UNKNOWN_17C = Flag::FromInfTable(0x17C);
    const Flag INFTABLE_UNKNOWN_17F = Flag::FromInfTable(0x17F);
    const Flag INFTABLE_UNKNOWN_190 = Flag::FromInfTable(0x190);
    const Flag INFTABLE_UNKNOWN_191 = Flag::FromInfTable(0x191);
    const Flag BOUGHT_STICK_UPGRADE = Flag::FromInfTable(0x192);
    const Flag BOUGHT_NUT_UPGRADE = Flag::FromInfTable(0x193);
    const Flag SPOKE_TO_KAEPORA_IN_LAKE_HYLIA = Flag::FromInfTable(0x195);
    const Flag INFTABLE_UNKNOWN_196 = Flag::FromInfTable(0x196);
    const Flag INFTABLE_UNKNOWN_197 = Flag::FromInfTable(0x197);
    const Flag INFTABLE_UNKNOWN_198 = Flag::FromInfTable(0x198);
    const Flag SWORDLESS = Flag::FromInfTable(0x1D0);
}
// clang-format on